// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WeatherForcastDemo.Entities
{
    public partial class BookCategory
    {
        public int Id { get; set; }
        public string CategoryTitle { get; set; } = null!;
        public string? CategoryDescription { get; set; }
        /// <summary>
        /// 所属的上一级图书分类ID号
        /// </summary>
        public int? ParentId { get; set; }
    }
}