// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WeatherForcastDemo.Entities
{
    public partial class Book
    {
        public int Id { get; set; }
        public string? IsbnCode { get; set; }
        public string? Title { get; set; }
        public string? Author { get; set; }
        public string? Publisher { get; set; }
        public int? Pages { get; set; }
    }
}